name: HadCM3B_60ka_for_LPJ-GUESS
channels:
  - conda-forge
  - r
dependencies:
  - make=4.2.1
  - nco=4.7.9
  - netCDF4=1.5.0.1
  - python=3.7
  - r-ggplot2=3.0.0
  - r-maps=3.3.0
  - scipy=1.2.1
  - xarray=0.12.0
