FROM debian:buster-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
      make=4.2.1-1.2 \
      nco=4.7.9-1 \
      python3-netcdf4=1.4.2-1+b1 \
      r-cran-ggplot2=3.1.0-1 \
      python3-scipy=1.1.0-7 \
      python3-xarray=0.11.3-2


